/**
 * FlashcardSourceSelector — 4 source tabs: Textbook, Web Link, Upload File, Paste Text.
 */

import { useState, useEffect, useRef, useCallback } from "react";
import {
  getTextbooks,
  uploadTextbook,
  generateFlashcardsFromTextbook,
  generateFlashcardsFromUrl,
  generateFlashcardsFromFile,
  generateFlashcardsFromText,
} from "../services/api";
import type { FlashcardItem } from "../services/api";
import { LoadingSpinner } from "./LoadingSpinner";
import { useNotification } from "../contexts/NotificationContext";
import { useAuth } from "../contexts/AuthContext";

const SUBJECTS = ["General", "Mathematics", "Physics", "Biology", "Chemistry", "History", "English"];
const CARD_OPTIONS = [5, 10, 15, 20] as const;

export type SourceTab = "textbook" | "weblink" | "upload" | "paste";

export interface FlashcardSourceSelectorProps {
  count: number;
  onCountChange: (n: number) => void;
  onGenerate: (cards: FlashcardItem[], sourceType: string[]) => void;
  loading?: boolean;
  error: string | null;
  onError: (msg: string | null) => void;
}

const ALLOWED_EXT = [".pdf", ".ppt", ".pptx"];
const PASTE_MIN = 150;
const PASTE_MAX = 3000;

export function FlashcardSourceSelector({
  count: initialCount,
  onCountChange,
  onGenerate,
  loading: loadingProp,
  error,
  onError,
}: FlashcardSourceSelectorProps) {
  const { push } = useNotification();
  const { connectivityStatus } = useAuth();
  const [tab, setTab] = useState<SourceTab>("textbook");
  const [internalLoading, setInternalLoading] = useState(false);
  const [uploading, setUploading] = useState(false);
  const loading = loadingProp ?? internalLoading;
  const [textbooks, setTextbooks] = useState<{ id: string; name: string }[]>([]);
  const [textbookMode, setTextbookMode] = useState<"existing" | "upload">("existing");
  const [selectedTextbook, setSelectedTextbook] = useState("");
  const [chapterInput, setChapterInput] = useState("");
  const [weblinkUrl, setWeblinkUrl] = useState("");
  const [pasteText, setPasteText] = useState("");
  const [subject, setSubject] = useState("General");
  const [numCards, setNumCards] = useState(initialCount ?? 10);
  const [uploadFile, setUploadFile] = useState<File | null>(null);
  const [isDragOver, setIsDragOver] = useState(false);
  const [uploadError, setUploadError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);
  const textbookFileInputRef = useRef<HTMLInputElement>(null);
  const [textbookUploadFileName, setTextbookUploadFileName] = useState<string | null>(null);
  const lastAutoGeneratedFileRef = useRef<string | null>(null);

  useEffect(() => {
    getTextbooks()
      .then((r) => setTextbooks(r.textbooks))
      .catch(() => setTextbooks([]));
  }, []);
  useEffect(() => {
    setNumCards(initialCount ?? 10);
  }, [initialCount]);

  const clearTabError = useCallback(() => {
    onError(null);
    setUploadError(null);
  }, [onError]);

  // Auto-generate flashcards when a file is added (Upload File tab)
  useEffect(() => {
    if (tab !== "upload" || !uploadFile) {
      if (!uploadFile) lastAutoGeneratedFileRef.current = null;
      return;
    }
    const fileKey = `${uploadFile.name}-${uploadFile.size}`;
    if (lastAutoGeneratedFileRef.current === fileKey) return;
    const ext = uploadFile.name.toLowerCase().slice(uploadFile.name.lastIndexOf("."));
    if (!ALLOWED_EXT.some((e) => ext === e)) return;

    lastAutoGeneratedFileRef.current = fileKey;
    clearTabError();
    setInternalLoading(true);
    generateFlashcardsFromFile({
      file: uploadFile,
      subject,
      num_cards: numCards,
    })
      .then((res) => {
        onGenerate(res.cards.map((c) => ({ ...c, sourceType: ["file"] })), ["file"]);
      })
      .catch((err) => {
        const msg = err instanceof Error ? err.message : "Generation failed.";
        push({ type: "error", title: "Auto-generate failed", message: msg });
        onError(msg);
        lastAutoGeneratedFileRef.current = null;
      })
      .finally(() => {
        setInternalLoading(false);
      });
  }, [uploadFile, tab, subject, numCards, onGenerate, onError, clearTabError]);

  const handleTextbookUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file || !file.name.toLowerCase().endsWith(".pdf")) {
      onError("Please select a PDF file.");
      return;
    }
    setTextbookUploadFileName(file.name);
    clearTabError();
    setUploading(true);
    try {
      const res = await uploadTextbook(file);
      setTextbooks((prev) => [...prev, { id: res.id, name: res.name }]);
      setSelectedTextbook(res.id);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Upload failed.";
      console.error("[FlashcardSourceSelector] Textbook upload failed:", err);
      push({ type: "error", title: "Upload failed", message: msg });
      onError(msg);
    } finally {
      setUploading(false);
      setTextbookUploadFileName(null);
    }
    e.target.value = "";
  };

  const handleGenerateTextbook = async () => {
    if (!selectedTextbook) {
      onError("Select or upload a textbook first.");
      return;
    }
    clearTabError();
    setInternalLoading(true);
    try {
      const res = await generateFlashcardsFromTextbook({
        textbook_id: selectedTextbook,
        chapter: chapterInput.trim() || undefined,
        count: numCards,
      });
      onGenerate(res.cards.map((c) => ({ ...c, sourceType: ["textbook"] })), ["textbook"]);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Generation failed.";
      console.error("[FlashcardSourceSelector] Textbook generation failed:", err);
      push({ type: "error", title: "Flashcard generation failed", message: msg });
      onError(msg);
    } finally {
      setInternalLoading(false);
    }
  };

  const handleGenerateWeblink = async () => {
    const url = weblinkUrl.trim();
    if (!url) {
      onError("Enter a valid URL.");
      return;
    }
    if (connectivityStatus === "offline") {
      push({
        type: "info",
        title: "Internet required",
        message: "You need to be connected to use web links.",
      });
      return;
    }
    clearTabError();
    setInternalLoading(true);
    try {
      const res = await generateFlashcardsFromUrl({
        url,
        subject,
        num_cards: numCards,
      });
      onGenerate(res.cards.map((c) => ({ ...c, sourceType: ["weblink"] })), ["weblink"]);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Generation failed.";
      push({ type: "error", title: "Web link generation failed", message: msg });
      onError(msg);
    } finally {
      setInternalLoading(false);
    }
  };

  const handleGenerateUpload = async () => {
    if (!uploadFile) {
      setUploadError("Select or drop a PDF or PPT file.");
      return;
    }
    const ext = uploadFile.name.toLowerCase().slice(uploadFile.name.lastIndexOf("."));
    if (!ALLOWED_EXT.some((e) => ext === e)) {
      setUploadError("Only PDF and PPT files are supported.");
      return;
    }
    clearTabError();
    setInternalLoading(true);
    try {
      const res = await generateFlashcardsFromFile({
        file: uploadFile,
        subject,
        num_cards: numCards,
      });
      onGenerate(res.cards.map((c) => ({ ...c, sourceType: ["file"] })), ["file"]);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Generation failed.";
      console.error("[FlashcardSourceSelector] Generate from file failed:", err);
      push({ type: "error", title: "File generation failed", message: msg });
      onError(msg);
    } finally {
      setInternalLoading(false);
    }
  };

  const handleGeneratePaste = async () => {
    const text = pasteText.trim();
    if (text.length < PASTE_MIN) {
      onError("Please paste at least a paragraph of text to generate flashcards from");
      return;
    }
    clearTabError();
    setInternalLoading(true);
    try {
      const res = await generateFlashcardsFromText({
        text,
        subject,
        num_cards: numCards,
      });
      onGenerate(res.cards.map((c) => ({ ...c, sourceType: ["paste"] })), ["paste"]);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "Generation failed.";
      push({ type: "error", title: "Paste generation failed", message: msg });
      onError(msg);
    } finally {
      setInternalLoading(false);
    }
  };

  const handleGenerate = () => {
    if (tab === "textbook") handleGenerateTextbook();
    else if (tab === "weblink") handleGenerateWeblink();
    else if (tab === "upload") handleGenerateUpload();
    else handleGeneratePaste();
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const f = e.target.files?.[0];
    if (!f) return;
    const ext = f.name.toLowerCase().slice(f.name.lastIndexOf("."));
    if (!ALLOWED_EXT.some((e) => ext === e)) {
      setUploadError("Only PDF and PPT files are supported");
      setUploadFile(null);
    } else {
      setUploadError(null);
      setUploadFile(f);
    }
    e.target.value = "";
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(false);
    const f = e.dataTransfer.files?.[0];
    if (!f) return;
    const ext = f.name.toLowerCase().slice(f.name.lastIndexOf("."));
    if (!ALLOWED_EXT.some((ex) => ext === ex)) {
      setUploadError("Only PDF and PPT files are supported");
      setUploadFile(null);
    } else {
      setUploadError(null);
      setUploadFile(f);
    }
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    setIsDragOver(true);
  };

  const handleDragLeave = () => setIsDragOver(false);

  const tabs: { key: SourceTab; icon: string; label: string }[] = [
    { key: "textbook", icon: "📚", label: "Textbook/Notes" },
    { key: "weblink", icon: "🌐", label: "Web Link" },
    { key: "upload", icon: "📄", label: "Upload File" },
    { key: "paste", icon: "✏️", label: "Paste Text" },
  ];

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap gap-2">
        {tabs.map(({ key, icon, label }) => (
          <button
            key={key}
            type="button"
            onClick={() => { setTab(key); clearTabError(); setUploadError(null); }}
            className={`px-4 py-2 rounded-xl text-sm font-medium transition-colors ${
              tab === key
                ? "bg-accent-blue text-white"
                : "border border-glass-border bg-surface-light text-primary hover:bg-surface-light/80"
            }`}
          >
            {icon} {label}
          </button>
        ))}
      </div>

      {tab === "textbook" && (
        <div className="space-y-4">
          <div className="flex gap-4">
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="radio"
                name="textbookMode"
                checked={textbookMode === "existing"}
                onChange={() => setTextbookMode("existing")}
                className="rounded border-glass-border accent-accent-blue"
              />
              <span className="text-sm text-primary">Existing textbooks</span>
            </label>
            <label className="flex items-center gap-2 cursor-pointer">
              <input
                type="radio"
                name="textbookMode"
                checked={textbookMode === "upload"}
                onChange={() => setTextbookMode("upload")}
                className="rounded border-glass-border accent-accent-blue"
              />
              <span className="text-sm text-primary">Upload new PDF</span>
            </label>
          </div>
          {textbookMode === "upload" && (
            <div className="flex flex-wrap items-center gap-3">
              <input
                ref={textbookFileInputRef}
                type="file"
                accept=".pdf"
                onChange={handleTextbookUpload}
                disabled={uploading}
                className="hidden"
                aria-label="Choose PDF file"
              />
              <button
                type="button"
                onClick={() => textbookFileInputRef.current?.click()}
                disabled={uploading}
                className="px-4 py-2 rounded-xl font-medium text-deep bg-accent-blue hover:bg-accent-blue/90 disabled:opacity-60 text-sm"
              >
                Choose File
              </button>
              <span className="text-sm text-primary/70">
                {textbookUploadFileName ? textbookUploadFileName : "No file chosen"}
              </span>
              {uploading && <p className="text-sm text-primary/70">Uploading PDF…</p>}
            </div>
          )}
          {textbookMode === "existing" && textbooks.length > 0 && (
            <div>
              <label className="block text-sm font-medium text-primary/90 mb-2">Select textbook</label>
              <select
                value={selectedTextbook}
                onChange={(e) => setSelectedTextbook(e.target.value)}
                className="w-full max-w-md px-4 py-2 rounded-lg border border-glass-border bg-surface-light text-primary"
              >
                <option value="">— Select —</option>
                {textbooks.map((t) => (
                  <option key={t.id} value={t.id}>
                    {t.name}
                  </option>
                ))}
              </select>
            </div>
          )}
          <div>
            <label className="block text-sm font-medium text-primary/90 mb-2">
              Chapter or topic (optional)
            </label>
            <input
              type="text"
              value={chapterInput}
              onChange={(e) => setChapterInput(e.target.value)}
              placeholder="e.g. Chapter 5 – Cell Biology"
              className="w-full max-w-md px-4 py-2 rounded-lg border border-glass-border bg-surface-light text-primary placeholder:text-primary/50"
            />
          </div>
          <div className="flex flex-wrap gap-4">
            <div>
              <label className="block text-sm font-medium text-primary/90 mb-1">Number of cards</label>
              <div className="flex gap-2">
                {CARD_OPTIONS.map((n) => (
                  <button
                    key={n}
                    type="button"
                    onClick={() => { setNumCards(n); onCountChange(n); }}
                    className={`px-3 py-1.5 rounded-lg text-sm font-medium ${
                      numCards === n
                        ? "bg-accent-blue text-white"
                        : "border border-glass-border bg-surface-light text-primary"
                    }`}
                  >
                    {n}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {tab === "weblink" && (
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-primary/90 mb-2">Paste a URL…</label>
            <input
              type="url"
              value={weblinkUrl}
              onChange={(e) => { setWeblinkUrl(e.target.value); clearTabError(); }}
              placeholder="https://example.com/article"
              className="w-full max-w-md px-4 py-2 rounded-lg border border-glass-border bg-surface-light text-primary placeholder:text-primary/50"
            />
            {tab === "weblink" && error && (
              <p className="mt-2 text-sm text-red-500" role="alert">{error}</p>
            )}
          </div>
          <div className="flex flex-wrap gap-4">
            <div>
              <label className="block text-sm font-medium text-primary/90 mb-1">Subject</label>
              <select
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="px-3 py-2 rounded-lg border border-glass-border bg-surface-light text-primary"
              >
                {SUBJECTS.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-primary/90 mb-1">Number of cards</label>
              <div className="flex gap-2">
                {CARD_OPTIONS.map((n) => (
                  <button
                    key={n}
                    type="button"
                    onClick={() => { setNumCards(n); onCountChange(n); }}
                    className={`px-3 py-1.5 rounded-lg text-sm font-medium ${
                      numCards === n
                        ? "bg-accent-blue text-white"
                        : "border border-glass-border bg-surface-light text-primary"
                    }`}
                  >
                    {n}
                  </button>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}

      {tab === "upload" && (
        <div className="space-y-4">
          <div
            onDrop={handleDrop}
            onDragOver={handleDragOver}
            onDragLeave={handleDragLeave}
            onClick={() => fileInputRef.current?.click()}
            className={`max-w-md border-2 border-dashed rounded-xl p-8 text-center cursor-pointer transition-colors ${
              isDragOver ? "border-accent-blue bg-accent-blue/5" : "border-glass-border bg-surface-light/50 hover:bg-surface-light"
            }`}
          >
            <input
              ref={fileInputRef}
              type="file"
              accept=".pdf,.ppt,.pptx"
              onChange={handleFileSelect}
              className="hidden"
            />
            {uploadFile ? (
              <p className="text-sm text-primary font-medium truncate">{uploadFile.name}</p>
            ) : (
              <p className="text-sm text-primary/70">No file chosen — drag & drop or click to browse</p>
            )}
          </div>
          {(uploadError || (tab === "upload" && error)) && (
            <p className="text-sm text-red-500" role="alert">{uploadError || error}</p>
          )}
          <div className="flex flex-wrap gap-4">
            <div>
              <label className="block text-sm font-medium text-primary/90 mb-1">Subject</label>
              <select
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="px-3 py-2 rounded-lg border border-glass-border bg-surface-light text-primary"
              >
                {SUBJECTS.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-primary/90 mb-1">Number of cards</label>
              <select
                value={numCards}
                onChange={(e) => { const v = Number(e.target.value); setNumCards(v); onCountChange(v); }}
                className="px-3 py-2 rounded-lg border border-glass-border bg-surface-light text-primary"
              >
                {CARD_OPTIONS.map((n) => (
                  <option key={n} value={n}>{n}</option>
                ))}
              </select>
            </div>
          </div>
        </div>
      )}

      {tab === "paste" && (
        <div className="space-y-4">
          <div>
            <label className="block text-sm font-medium text-primary/90 mb-2">
              Paste your notes, an article, or any text here…
            </label>
            <textarea
              value={pasteText}
              onChange={(e) => {
                const v = e.target.value;
                if (v.length <= PASTE_MAX) setPasteText(v);
                clearTabError();
              }}
              placeholder="Paste your notes, an article, or any text here…"
              maxLength={PASTE_MAX}
              rows={8}
              className="w-full max-w-2xl px-4 py-2 rounded-lg border border-glass-border bg-surface-light text-primary placeholder:text-primary/50 resize-y"
            />
            <p className="mt-1 text-xs text-primary/60">
              {pasteText.length} / {PASTE_MAX}
            </p>
            {(tab === "paste" && error) && (
              <p className="mt-2 text-sm text-red-500" role="alert">{error}</p>
            )}
          </div>
          <div className="flex flex-wrap gap-4">
            <div>
              <label className="block text-sm font-medium text-primary/90 mb-1">Subject</label>
              <select
                value={subject}
                onChange={(e) => setSubject(e.target.value)}
                className="px-3 py-2 rounded-lg border border-glass-border bg-surface-light text-primary"
              >
                {SUBJECTS.map((s) => (
                  <option key={s} value={s}>{s}</option>
                ))}
              </select>
            </div>
            <div>
              <label className="block text-sm font-medium text-primary/90 mb-1">Number of cards</label>
              <select
                value={numCards}
                onChange={(e) => { const v = Number(e.target.value); setNumCards(v); onCountChange(v); }}
                className="px-3 py-2 rounded-lg border border-glass-border bg-surface-light text-primary"
              >
                {CARD_OPTIONS.map((n) => (
                  <option key={n} value={n}>{n}</option>
                ))}
              </select>
            </div>
          </div>
        </div>
      )}


      {error && tab !== "weblink" && tab !== "upload" && tab !== "paste" && (
        <p className="text-sm text-red-500" role="alert">{error}</p>
      )}

      <LoadingSpinner loading={loading} message="Generating flashcards...">
        <button
          type="button"
          onClick={handleGenerate}
          disabled={loading}
          className="px-5 py-2.5 rounded-xl font-medium text-deep bg-accent-blue hover:bg-accent-blue/90 focus:outline-none focus:ring-2 focus:ring-accent-blue disabled:opacity-60"
        >
          Generate Flashcards
        </button>
      </LoadingSpinner>
    </div>
  );
}
